### ISSUE TITLE
Unable to tangle using org-tangle; no errors

### ISSUE THREAD

**Issue by kaushalmodi** [parsing-tech/org-rs#1]
Hello,

I was able to install `org-tangle` using the nightly build of Rust.

I quickly tried it out on [one of the test files][1] for my Nim implementation [ntangle][2], but nothing got tangled out of it.

```
> org-tangle ./tangle_no_yes.org
- tangle : "/home/kmodi/stow/pub_dotfiles/emacs/dot-emacs.d/misc/ntangle/tests/tangle_no_yes/./tangle_no_yes.org"
```

Expected tangled files ([test dir][3]):
- https://raw.githubusercontent.com/OrgTangle/ntangle/master/tests/tangle_no_yes/tangle_no_yes.nim
- https://raw.githubusercontent.com/OrgTangle/ntangle/master/tests/tangle_no_yes/specified_file.nim

What am I missing?

---

### Test file

```org
#+begin_src nim :tangle no
echo "this block won't get tangled"
#+end_src

#+begin_src nim :tangle yes
echo "this will be tangled to tangle_no_yes.nim"
#+end_src

#+begin_src nim :tangle specified_file.nim
echo "this will be tangled to specified_file.nim"
#+end_src
```

[1]: https://raw.githubusercontent.com/OrgTangle/ntangle/master/tests/tangle_no_yes/tangle_no_yes.org
[2]: https://github.com/OrgTangle/ntangle/blob/master/README.org
[3]: https://github.com/OrgTangle/ntangle/tree/master/tests/tangle_no_yes

**Comment by xieyuheng** [comment]
Currently only global tangle property-line is supported.
(because I only use global tangle property-line >_<)

This means only the following simple use case is covered :

```
#+property: tangle specified_file.nim

#+begin_src nim
echo "this will be tangled to specified_file.nim"
#+end_src
```

**Comment by xieyuheng** [comment]
I add some notes in the readme :: https://github.com/parsing-tech/org-rs/tree/master/org-tangle#note-about-restriction

Maybe when I need to use
code block level tangle property-line
and headline level tangle property-line,
I will handle them in this program.

**Comment by kaushalmodi** [comment]
Hehe, I on the other hand need to add support (ntangle) for global property and subtree level property headers :P
