### ISSUE TITLE
Incorrect #+property syntax for enabling tangling

### ISSUE THREAD

**Issue by kaushalmodi** [parsing-tech/org-rs#2]
Hello,

As I am working to enable global property based tangling, I got curious and checked out the test Org file used by your project: https://raw.githubusercontent.com/parsing-tech/org-rs/master/org-tangle-engine/src/engine.org

I opened that file in Emacs, and did `C-v C-v t` (default binding for `org-babel-tangle`), but I got "Tangled 0 code blocks from engine.org".

Then carefully looking at the property keyword, I notice that you have the wrong syntax.

### Wrong

```org
#+property: tangle lib.rs
```

### Right

```org
#+property: header-args :tangle lib.rs
```

Upon fixing that, and running `C-c C-v t` again, I see the `lib.rs` generated and I see the message "Tangled 14 code blocks from engine.org".

**Comment by xieyuheng** [comment]
It works for me :
![tangle](https://img.vim-cn.com/4b/fab571eeb0ea853fa273332128b8ec64697962.png)

Maybe I am using an old version of org-mode.
Let me check it.

**Comment by kaushalmodi** [comment]
Yeah, you are probably on Org 8.x.

This was a backward incompatible change in Org 9.0: https://code.orgmode.org/bzg/org-mode/src/master/etc/ORG-NEWS#L1042

**Comment by xieyuheng** [comment]
Thansk for pointing this syntax change out

The problem is fixed in org-tangle v0.1.5
Now both old syntax and new syntax are supported

Try it by `cargo install org-tangle --force`

close this issue after the fix is confirmed

**Comment by xieyuheng** [comment]
sorry I accidentally closed this issue

**Comment by kaushalmodi** [comment]
Thanks. It's working now. Though I don't know if this is intended. The whole tangled file has a 2-space indentation. I used this: https://raw.githubusercontent.com/OrgTangle/ntangle/master/tests/org_tangle_rs/engine.org. I'll close this issue as you now support the new syntax.

**Comment by xieyuheng** [comment]
I didn't handle indentation >_<

I will fix them in another issue

**Comment by xieyuheng** [comment]
@kaushalmodi https://github.com/parsing-tech/org-rs/issues/3
