### ISSUE TITLE
generate pretty output

### ISSUE THREAD

**Issue by xieyuheng** [parsing-tech/org-rs#3]
generate pretty output

- one newline per block
- without extra indentation

**Comment by xieyuheng** [comment]
I will do it tomorrow

**Comment by xieyuheng** [comment]
I found that, if I write the commit message as `fix https://github.com/parsing-tech/org-rs/issues/3`
the issue will be auto-closed by github ...

**Comment by xieyuheng** [comment]
@kaushalmodi
this is also fixed
again, try it by cargo install org-tangle --force

**Comment by xieyuheng** [comment]
found this https://help.github.com/articles/closing-issues-using-keywords/

**Comment by xieyuheng** [comment]
I will be careful next time.
Normally, issue should be closed by reporter.

**Comment by kaushalmodi** [comment]
> I found that, if I write the commit message as fix https://github.com/parsing-tech/org-rs/issues/3
the issue will be auto-closed by github

I actually like, and use that feature.

Don't worry about auto-closing issues :). I am fine with that.

> again, try it by cargo install org-tangle --force

Just FYI, to save disk space, I removed the stable channel and have just the nightly installed. So I do: `cargo +nightly install org-tangle --force` (thanks for the `+nightly` tip you gave earlier).

---

I confirm the fix! The only minor thing is that compared to `C-c C-v t` output, `org-tangle` always appends a blank line at the end of the tangled files.

![image](https://user-images.githubusercontent.com/3578197/46620917-13ee1080-caf4-11e8-82c4-3e711a0bbd91.png)

**Comment by xieyuheng** [comment]
if you only need nightly toolchain
you can `rustup default nightly`
and `cargo install org-tangle --force`
(instead of `cargo +nightly install org-tangle --force`)

**Comment by xieyuheng** [comment]
extra blank line is fixed now

**Comment by xieyuheng** [comment]
I am about to finish a parser generator very soon.
with the help of a parser generator, I will try to really parse org-mode.
(although org-mode does not have a syntax specification)

**Comment by kaushalmodi** [comment]
> although org-mode does not have a syntax specification

There is this spec: https://orgmode.org/worg/dev/org-syntax.html
